# Generated by Django 5.2.1 on 2025-05-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamento', '0008_alter_equipamento_ca'),
        ('usuario', '0020_funcionario_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_padrao', to='usuario.funcionario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_padrao', to='usuario.setor')),
            ],
        ),
        migrations.CreateModel(
            name='PadraoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.padrao')),
            ],
            options={
                'unique_together': {('padrao', 'equipamento')},
            },
        ),
        migrations.AddField(
            model_name='padrao',
            name='itens',
            field=models.ManyToManyField(related_name='equipamento_padrao', through='padrao.PadraoEquipamento', to='equipamento.equipamento'),
        ),
    ]
