# Generated by Django 5.2.1 on 2025-05-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Padrao',
        ),
    ]
