# Generated by Django 5.2.1 on 2025-05-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0008_alter_equipamento_ca'),
        ('padrao', '0001_initial'),
        ('usuario', '0022_alter_usuario_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrao',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='padrao',
            name='itens',
        ),
        migrations.CreateModel(
            name='PadraoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.funcionario')),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao.padrao')),
            ],
            options={
                'unique_together': {('padrao', 'funcionario')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='padraoequipamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='padrao',
            name='funcionarios',
            field=models.ManyToManyField(related_name='padroes', through='padrao.PadraoFuncionario', to='usuario.funcionario'),
        ),
        migrations.AddField(
            model_name='padraoequipamento',
            name='padrao_funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='padrao.padraofuncionario'),
        ),
        migrations.AlterUniqueTogether(
            name='padraoequipamento',
            unique_together={('padrao_funcionario', 'equipamento')},
        ),
        migrations.RemoveField(
            model_name='padraoequipamento',
            name='padrao',
        ),
    ]
