# Generated by Django 5.2.1 on 2025-05-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0002_remove_padrao_funcionario_remove_padrao_itens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraoequipamento',
            name='padrao_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='padrao.padraofuncionario'),
        ),
    ]
