# Generated by Django 5.0.6 on 2025-05-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padrao',
            old_name='cargo',
            new_name='nome',
        ),
    ]
