# Generated by Django 5.2.1 on 2025-05-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0004_alter_padraoequipamento_padrao_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraoequipamento',
            name='padrao_funcionario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='padrao.padraofuncionario'),
        ),
    ]
