# Generated by Django 5.2.1 on 2025-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0006_alter_padraoequipamento_padrao_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
