# Generated by Django 5.2.1 on 2025-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padrao', '0008_remove_padrao_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padraoequipamento',
            name='motivo',
            field=models.CharField(choices=[('primeira entrega', 'Primeira Entrega'), ('substituicao', 'Substituição'), ('devolucao', 'Devolução')], default='substituicao', max_length=20),
        ),
    ]
