# Generated by Django 5.2.1 on 2025-08-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemresposta',
            name='pergunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pergunta', to='checklist.pergunta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='checklist.checklist'),
        ),
    ]
