# Generated by Django 5.2.4 on 2025-08-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_itemresposta_pergunta_alter_pergunta_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist', verbose_name='checklist'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='checklist.checklist'),
        ),
    ]
