# Generated by Django 5.2.1 on 2025-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_inspecao_checklist_alter_pergunta_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresposta',
            name='texto_checklist_historico',
            field=models.TextField(default=1),
        ),
    ]
