# Generated by Django 5.2.1 on 2025-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_itemresposta_texto_checklist_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemresposta',
            name='texto_checklist_historico',
            field=models.TextField(),
        ),
    ]
