# Generated by Django 5.2.1 on 2025-08-21 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_itemresposta_texto_checklist_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecao',
            options={'ordering': ['-data_inspecao']},
        ),
        migrations.AlterField(
            model_name='itemresposta',
            name='inspecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_resposta', to='checklist.inspecao'),
        ),
        migrations.AlterField(
            model_name='itemresposta',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
