# Generated by Django 5.2.1 on 2025-08-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_inspecao_options_alter_itemresposta_inspecao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemresposta',
            name='texto_checklist_historico',
        ),
    ]
