# Generated by Django 5.2.1 on 2025-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_remove_itemresposta_texto_checklist_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
