# Generated by Django 5.2.1 on 2025-08-21 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_checklist_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
