# Generated by Django 5.2.4 on 2025-08-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_checklist_created_at_checklist_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresposta',
            name='acoes_corretivas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemresposta',
            name='causas_reprovacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
