# Generated by Django 5.2.4 on 2025-08-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_itemresposta_acoes_corretivas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresposta',
            name='descricao_checklist_historico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemresposta',
            name='nome_checklist_historico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
