# Generated by Django 5.2.4 on 2025-08-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_itemresposta_descricao_checklist_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresposta',
            name='data_resposta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
