# Generated by Django 5.2.4 on 2025-08-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_itemresposta_data_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemresposta',
            name='id_checklist_historico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemresposta',
            name='id_pergunta_historico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemresposta',
            name='nome_checklist_historico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='checklist.checklist'),
        ),
    ]
