# Generated by Django 5.2.4 on 2025-08-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_itemresposta_id_checklist_historico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemresposta',
            name='data_resposta',
        ),
        migrations.RemoveField(
            model_name='itemresposta',
            name='descricao_checklist_historico',
        ),
        migrations.RemoveField(
            model_name='itemresposta',
            name='id_checklist_historico',
        ),
        migrations.RemoveField(
            model_name='itemresposta',
            name='id_pergunta_historico',
        ),
        migrations.RemoveField(
            model_name='itemresposta',
            name='nome_checklist_historico',
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='checklist.checklist'),
        ),
    ]
