# Generated by Django 5.2.4 on 2025-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0014_remove_itemresposta_data_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
