# Generated by Django 5.2.4 on 2025-08-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_pergunta_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='descricao',
        ),
    ]
