# Generated by Django 5.2.4 on 2025-08-25 14:09

import checklist.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_remove_pergunta_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=checklist.models.foto_upload_path, verbose_name='Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('item_resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='checklist.itemresposta', verbose_name='Resposta da pergunta')),
            ],
            options={
                'verbose_name': 'Foto da Resposta',
                'verbose_name_plural': 'Fotos das Respostas',
                'ordering': ['data_upload'],
            },
        ),
    ]
