# Generated by Django 5.2.4 on 2025-08-27 11:22

import checklist.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0017_fotoresposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoresposta',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=checklist.models.foto_upload_path, verbose_name='Foto'),
        ),
    ]
