# Generated by Django 5.2.8 on 2026-09-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0018_alter_fotoresposta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='maquina_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='maquina_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
