# Generated by Django 5.2.8 on 2026-09-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_checklist_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemresposta',
            name='conformidade',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
