# Generated by Django 5.2.1 on 2025-05-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devolucao', '0001_initial'),
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='responsavel_recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_recebimento', to='solicitacao.solicitacao'),
        ),
        migrations.AddField(
            model_name='devolucao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_devolucao', to='solicitacao.solicitacao'),
        ),
    ]
