# Generated by Django 5.2.1 on 2025-07-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0002_initial'),
        ('usuario', '0026_cargo_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucao',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='devolucao',
            name='estado_item',
            field=models.CharField(choices=[('bom', 'Bom'), ('ruim', 'Ruim'), ('danificado', 'Danificado')], default='bom', max_length=30),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='responsavel_recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_recebimento', to='usuario.funcionario'),
        ),
    ]
