# Generated by Django 5.0.6 on 2025-07-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0004_remove_devolucao_motivo'),
        ('solicitacao', '0015_alter_assinatura_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_solicitacao_devolucao', to='solicitacao.dadossolicitacao'),
        ),
    ]
