# Generated by Django 5.0.6 on 2025-07-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0005_alter_devolucao_solicitacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucao',
            old_name='solicitacao',
            new_name='dados_solicitacao',
        ),
    ]
