# Generated by Django 5.2.1 on 2025-07-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0007_alter_devolucao_responsavel_recebimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
