# Generated by Django 5.2.1 on 2025-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0008_devolucao_quantidade_devolvida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='quantidade_devolvida',
            field=models.PositiveIntegerField(),
        ),
    ]
