# Generated by Django 5.2.1 on 2025-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_admissao',
            field=models.DateField(null=True),
        ),
    ]
