# Generated by Django 5.2.1 on 2025-05-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_data_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.IntegerField(unique=True)),
                ('setor', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('data_admissao', models.DateField(null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='setor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_acesso',
            field=models.CharField(choices=[('master', 'Master'), ('solicitante', 'Solicitante'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcionario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='usuario.funcionario'),
        ),
    ]
