# Generated by Django 5.2.1 on 2025-05-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_funcionario_setor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
