# Generated by Django 5.2.1 on 2025-05-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_funcionario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcionario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='usuario.funcionario'),
        ),
    ]
