# Generated by Django 5.2.1 on 2025-05-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_alter_usuario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_funcionario', to='usuario.funcionario'),
        ),
    ]
