# Generated by Django 5.0.6 on 2025-05-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_funcionario_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='responsavel',
        ),
    ]
