# Generated by Django 5.2.1 on 2025-05-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_funcionario_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcionario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to='usuario.funcionario'),
        ),
    ]
