# Generated by Django 5.2.1 on 2025-05-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_remove_funcionario_responsavel_setor_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='responsavel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel', to='usuario.funcionario'),
        ),
    ]
