# Generated by Django 5.2.1 on 2025-05-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_alter_setor_responsavel'),
        ('usuario', '0022_alter_usuario_funcionario'),
    ]

    operations = [
    ]
