
# Generated by Django 5.2.1 on 2025-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_merge_20250530_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_acesso',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_acesso',
            field=models.CharField(choices=[('master', 'Master'), ('solicitante', 'Solicitante'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
