# Generated by Django 5.2.1 on 2025-06-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_merge_20250530_1711'),
        ('usuario', '0024_remove_usuario_tipo_acesso_funcionario_tipo_acesso'),
    ]

    operations = [
    ]
