# Generated by Django 5.2.1 on 2025-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_alter_usuario_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
