# Generated by Django 5.2.4 on 2026-03-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_alter_funcionario_data_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dds_criados', to='usuario.usuario')),
                ('participantes', models.ManyToManyField(related_name='dds_participados', to='usuario.funcionario')),
            ],
            options={
                'verbose_name': 'DDS',
                'verbose_name_plural': 'DDS',
                'ordering': ['-data', '-horario', '-id'],
            },
        ),
    ]
