# Generated by Django 5.2.4 on 2026-03-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_dds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dds',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dds_responsavel', to='usuario.funcionario'),
        ),
    ]
