# Generated by Django 5.2.4 on 2026-03-11 00:00

import storages.backends.s3boto3
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0030_dds_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDSAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_assinatura', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='assinatura/dds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='usuario.dds')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dds_assinaturas', to='usuario.funcionario')),
            ],
            options={
                'verbose_name': 'Assinatura DDS',
                'verbose_name_plural': 'Assinaturas DDS',
                'unique_together': {('dds', 'funcionario')},
            },
        ),
    ]
