# Generated by Django 5.1.1 on 2024-09-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('vida_util', models.IntegerField(blank=True, help_text='Vida útil do item (em dias)', null=True)),
                ('ca', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
