# Generated by Django 5.1.1 on 2024-09-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitadoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('primeira_entrega', models.BooleanField(default=False)),
                ('motivo', models.CharField(choices=[('perda', 'Perda'), ('substituicao', 'Substituição'), ('dano', 'Dano')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinada', 'Assinada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('motivo_rejeitada', models.CharField(blank=True, max_length=50, null=True)),
                ('primeira_entrega', models.BooleanField(default=False)),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('motivo', models.CharField(choices=[('perda', 'Perda'), ('substituicao', 'Substituição'), ('dano', 'Dano')], max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_solicitacao', to='cadastro.item')),
            ],
        ),
    ]
