# Generated by Django 5.1.1 on 2024-09-19 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('solicitacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitado',
            name='liderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsolicitadopadrao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_padrao_solicitacao', to='cadastro.item'),
        ),
        migrations.AddField(
            model_name='itemsolicitadopadrao',
            name='liderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_padrao_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_lider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='liderado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_liderado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsolicitado',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitados', to='solicitacao.solicitacao'),
        ),
        migrations.AddField(
            model_name='solicitacaopadrao',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_padrao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsolicitadopadrao',
            name='solicitacao_padrao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_padrao', to='solicitacao.solicitacaopadrao'),
        ),
    ]
