# Generated by Django 5.2.1 on 2025-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_initial'),
        ('usuario', '0026_cargo_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='funcionarios',
            field=models.ManyToManyField(related_name='solicitacoes', to='usuario.funcionario'),
        ),
    ]
