# Generated by Django 5.2.1 on 2025-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_alter_solicitacao_responsavel_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='motivo',
            field=models.CharField(choices=[('primeira entrega', 'Primeira Entrega'), ('substituicao', 'Substituição'), ('perda', 'Perda'), ('dano', 'Dano')], default='substituicao', max_length=20),
        ),
    ]
