# Generated by Django 5.2.1 on 2025-06-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_solicitacao_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='motivo',
        ),
    ]
