# Generated by Django 5.2.1 on 2025-06-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_remove_solicitacao_data_criacao'),
        ('usuario', '0026_cargo_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='funcionarios',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='responsavel_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_entrega', to='usuario.funcionario'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.funcionario'),
        ),
    ]
