# Generated by Django 5.2.1 on 2025-06-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0010_assinatura_remove_solicitacao_responsavel_entrega'),
        ('usuario', '0026_cargo_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.funcionario'),
        ),
    ]
