# Generated by Django 5.2.1 on 2025-07-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0011_solicitacao_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='solicitacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinatura_solicitacao', to='solicitacao.solicitacao'),
        ),
    ]
