# Generated by Django 5.2.1 on 2025-07-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0012_assinatura_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='solicitacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_solicitacao', to='solicitacao.solicitacao'),
        ),
    ]
