# Generated by Django 5.2.1 on 2025-07-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0014_delete_dadossolicitacao'),
        ('solicitacao', '0013_alter_assinatura_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(choices=[('primeira entrega', 'Primeira Entrega'), ('substituicao', 'Substituição'), ('perda', 'Perda'), ('dano', 'Dano')], default='substituicao', max_length=20)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_equipamento', to='equipamento.equipamento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_solicitacao', to='solicitacao.solicitacao')),
            ],
            options={
                'unique_together': {('equipamento', 'solicitacao')},
            },
        ),
    ]
