# Generated by Django 5.2.1 on 2025-07-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0014_dadossolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='solicitacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.solicitacao'),
        ),
    ]
