# Generated by Django 5.2.4 on 2025-08-27 11:22

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0015_alter_assinatura_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='imagem_assinatura',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='assinatura/'),
        ),
    ]
