# Generated by Django 5.2.8 on 2026-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0016_alter_assinatura_imagem_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossolicitacao',
            name='controlar_uso',
            field=models.BooleanField(default=True),
        ),
    ]
