# Generated by Django 5.2.1 on 2025-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='vida_util_dias',
            field=models.IntegerField(default=0),
        ),
    ]
