# Generated by Django 5.2.1 on 2025-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_equipamento_ca_equipamento_vida_util_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='ca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='vida_util_dias',
            field=models.IntegerField(),
        ),
    ]
