# Generated by Django 5.2.1 on 2025-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_alter_equipamento_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='vida_util_dias',
            field=models.IntegerField(default=365),
        ),
    ]
