# Generated by Django 5.2.1 on 2025-05-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0004_alter_equipamento_vida_util_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
    ]
