# Generated by Django 5.2.1 on 2025-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0005_remove_equipamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='ca',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
