# Generated by Django 5.2.1 on 2025-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0007_alter_equipamento_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='ca',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
