# Generated by Django 5.2.1 on 2025-06-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0008_alter_equipamento_ca'),
        ('solicitacao', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='equipamento.equipamento')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_equipamento', to='solicitacao.solicitacao')),
            ],
        ),
    ]
