# Generated by Django 5.2.1 on 2025-06-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0010_equipamentosolicitacao_motivo'),
        ('solicitacao', '0007_remove_solicitacao_data_criacao'),
        ('usuario', '0026_cargo_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(choices=[('primeira entrega', 'Primeira Entrega'), ('substituicao', 'Substituição'), ('perda', 'Perda'), ('dano', 'Dano')], default='substituicao', max_length=20)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_equipamento', to='equipamento.equipamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_funcionario', to='usuario.funcionario')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_solicitacao', to='solicitacao.solicitacao')),
            ],
        ),
        migrations.DeleteModel(
            name='EquipamentoSolicitacao',
        ),
    ]
