# Generated by Django 5.2.1 on 2025-06-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0012_alter_dadossolicitacao_unique_together'),
        ('solicitacao', '0011_solicitacao_funcionario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dadossolicitacao',
            unique_together={('equipamento', 'solicitacao')},
        ),
        migrations.RemoveField(
            model_name='dadossolicitacao',
            name='funcionario',
        ),
    ]
