# Generated by Django 5.2.1 on 2025-07-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0013_alter_dadossolicitacao_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosSolicitacao',
        ),
    ]
