# Generated by Django 5.2.8 on 2026-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0014_delete_dadossolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tem_vida_util',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='vida_util_dias',
            field=models.IntegerField(blank=True, default=365, null=True),
        ),
    ]
